spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://ep-fancy-waterfall-a163vz5f-pooler.ap-southeast-1.aws.neon.tech/order?sslmode=require&channel_binding=require
